# ExceptionTest

```java
package day11;

public class ExceptionTest1 {

	public static void main(String[] args) throws InterruptedException { //throws 사용하여 예외 처리
		System.out.println("출력 시작");
		Thread.sleep(3000);       // 여기서 Interrupted 오류 발생
		System.out.println("출력 종료");
	}

}
```

throws 는 예외 처리

throw 는 예외 입력

```java
ackage day11;		
//�������� �θ�Ŭ������ Exception �̶�� Ŭ����
public class ExceptionTest2 {

	public static void main(String[] args) {
		System.out.println("�������");
		try {						//���ܰ� �߻��� ���� �ִ� �ڵ�, �� ���� �߻� �ڵ常 �ִ°� �ƴϴ�.
			int num1 = Integer.parseInt(args[0]);
			int num2 = Integer.parseInt(args[1]);
			int result = num1/num2;		//���� �߻��ϴ� ��ġ
			System.out.println("���� ��� : "+result);
		}catch(ArrayIndexOutOfBoundsException e) {	//���� ���� ĳġ������ ���� ó���ϸ� �ٽ� �ö�
			System.out.println("���α׷� �ƱԸ�Ʈ�� 2�� �����ϼ���!!");
		}catch(ArithmeticException e) {			//0���� ������� �߻�
			e.printStackTrace();				//e ���� ����Ͽ� call stack ���� ���� ���(�񵿱����)
			System.out.println("�ι��� ���α׷� �ƱԸ�Ʈ�� 0�� �ƴ� ���� �����ϼ���!!");
			return;
		}catch (Exception e) {		//�θ� Ŭ�����̱⿡ �ڼ� Ŭ������ ��ü�� ���� �� �ִ�.
									//�θ� Ŭ������ ���� �Ʒ� ��ġ���Ѿ� �Ѵ�
									//���� ����ϸ� ��� ���ܸ� �� ��Ƴ�������
//		}catch (NumberFormatException e) {
			e.printStackTrace();
			System.out.println("���α׷� �ƱԸ�Ʈ�� ���ڸ� �����ϼ���!!");
		}finally {
			System.out.println("�׻����!!");	
		}
		System.out.println("��������!!");
	}

}
```

수정하기

```java
package day11;
import java.util.Random;
class TestException extends Exception {
	TestException(String message){
		super(message);		//�����޽����� ���
	}
}
public class ExceptionTest3 {
	public static void main(String[] args)  {
		System.out.println("main()�������");
		a();
		System.out.println("main()��������");
	}
	static void a()  {	//try, catch�� �� ���� throws �� �� �ʿ����.
		System.out.println("a()�������");
		try {
			b();
		} catch (TestException e){	
			System.out.println("���� �߻� : "+e.getMessage());
		}
		System.out.println("a()��������");
	}
	static void b() throws TestException {	//b�� ȣ���� c�� ������ �߻��� �� ������ ȣ���� ������ �ѱ�ڴ�.
		System.out.println("b()�������");
		c();
		System.out.println("b()��������");
	}
	static void c() throws TestException { //throws TestException �� ���ָ� ���� �ְ���� ������ ������
		System.out.println("c()�������");
		boolean flag = new Random().nextBoolean();	//������ �ȴ�� �ٷ� �� Random ����,,�ѹ��� ��� ����,,���� true or false
		if(flag){
			throw new TestException("<<:::::�׽�Ʈ�� ���ܹ߻���Ŵ:::::>>");
		}else {
			System.out.println("��������");
		}	
		System.out.println("c()��������");
	}	
}
```

